### ISSUE TITLE
Warning: Can't find your Modernizr development build at bower_components/modernizr/modernizr.js

### ISSUE THREAD

**Issue by eversoclever** [robinpokorny/generator-lessapp#13]
Looking for Modernizr references
Warning: Can't find your Modernizr development build at bower_components/modernizr/modernizr.js
       grunt-modernizr needs this path to avoid false positives

       Update your gruntfile via the modernizr.devFile config option
       See https://github.com/doctyper/grunt-modernizr#devfile-string for more details

       Use --force to continue.

Aborted due to warnings.

**Comment by robinpokorny** [comment]
I believe this should be fixed now in v0.5.1.
