### ISSUE TITLE
Grunt serve - No fonts

### ISSUE THREAD

**Issue by tiagotedsky** [robinpokorny/generator-lessapp#9]
Hi, 
First thank you for this generator. 

I found a problem when we serve the app, the fonts dont get rendered, as you can see on the attached picture. 

![captura de ecra 2014-05-11 as 23 38 11](https://cloud.githubusercontent.com/assets/776452/2939846/fd02d3e8-d95c-11e3-9a1b-2cf9a831e503.png)

Thanks.

**Comment by sirchris** [comment]
You didn't fix it. Problem still exists and it's quite annoying :-1:

**Comment by sirchris** [comment]
@robinpokorny you didn't fix it :-1: Problem still exists and it's quite annoying

**Comment by sirchris** [comment]
@robinpokorny you didn't fix it :-1: Problem exists until build and it's quite annoying.
